# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 23:12
from __future__ import unicode_literals

import apps.form_test.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45, validators=[apps.form_test.models.validate_length_of_two])),
                ('last_name', models.CharField(max_length=45, validators=[apps.form_test.models.validate_length_of_two])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=100, validators=[apps.form_test.models.validate_pw_length])),
                ('dob', models.DateField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
