# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegistration', '0002_auto_20170220_2314'),
        ('course_reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loginRegistration.User'),
            preserve_default=False,
        ),
    ]
