# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_reg', '0002_courses_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to='loginRegistration.User'),
        ),
    ]
