# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegistration', '0002_auto_20170220_2314'),
        ('course_reg', '0003_auto_20170221_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='users',
        ),
        migrations.AddField(
            model_name='courses',
            name='users',
            field=models.ManyToManyField(related_name='user_courses', to='loginRegistration.User'),
        ),
    ]
